### ISSUE TITLE
Track moving objects.

### ISSUE THREAD

**Issue by Enturk** [dikshantad/SeeAndSeek#1]
The software needs to take in a video stream, and identify moving objects. 

- [ ] During a first step, this can be against a fixed background. 
- [ ] Later, it needs to be able to do it in a variety of backgrounds. 
- [ ] Finally, it needs to be able to do it against a constantly changing background.
- [ ] Objects must be able to merge and split, and continue to be tracked.

**Comment by dikshantad** [comment]
Moved to projects.
